### ISSUE TITLE
Vagrant box add problem 'URL using bad/illegal format or missing URL'

### ISSUE THREAD

**Issue by marjanovich** [udacity/devops-intro-project#101] opened 2021-05-30 16:46 UTC
vagrant box add ubuntu-14.04.6-server-amd64-appserver_virtualbox.box --name devops-appserver
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'devops-appserver' (v0) for provider:
    box: Unpacking necessary files from: file://C/Users/marja/Desktop/packer-templates/devops/packer-templates/virtualbox/ubuntu-14.04.6-server-amd64-appserver_virtualbox.box
    box:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

URL using bad/illegal format or missing URL

**Comment by 13rac1** [comment] 2021-06-03 22:59
duplicate of #91

**Closed as completed by 13rac1** 2021-06-03 22:59 UTC
